[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["fluent-ffmpeg", "@huggingface/inference"]
  included_files = ["node_modules/fluent-ffmpeg/**/*"]

[functions.api-transcribe]
  maxDuration = 300
  memory = 3008
  timeout = 300
